use TMD
go

-- Agregar registros a FORMULARIO_EVALUACION
INSERT INTO GD.FORMULARIO_EVALUACION
(FECHA_CREACION,NOMBRE,FECHA_ASIGNACION,ESTADO)
VALUES ('20130121','Desempeño Area de Sistemas','20130121','Asignado')


-- Agregar registros a FORMULARIO_EVALUACION_CALIFICACION
INSERT INTO GD.FORMULARIO_EVALUACION_CALIFICACION VALUES (1,1,1,1)
INSERT INTO GD.FORMULARIO_EVALUACION_CALIFICACION VALUES (1,1,1,2)
INSERT INTO GD.FORMULARIO_EVALUACION_CALIFICACION VALUES (1,1,2,10)
INSERT INTO GD.FORMULARIO_EVALUACION_CALIFICACION VALUES (1,1,3,12)

-- Agregar registros a FORMULARIO_EVALUACION_SECCION
INSERT INTO GD.FORMULARIO_EVALUACION_SECCION VALUES (1,1,1)
INSERT INTO GD.FORMULARIO_EVALUACION_SECCION VALUES (1,1,2)
INSERT INTO GD.FORMULARIO_EVALUACION_SECCION VALUES (1,2,3)
INSERT INTO GD.FORMULARIO_EVALUACION_SECCION VALUES (1,2,4)
INSERT INTO GD.FORMULARIO_EVALUACION_SECCION VALUES (1,2,5)
INSERT INTO GD.FORMULARIO_EVALUACION_SECCION VALUES (1,3,6)

-- Agregar registros a FORMULARIO_EVALUACION_EMPLEADO
INSERT INTO GD.FORMULARIO_EVALUACION_EMPLEADO
(CODIGO_FORMULARIO_EVALUACION,CODIGO_EMPLEADO,CODIGO_EVALUADOR,FECHA_VIGENCIA,FECHA_EVALUADO,ESTADO)
VALUES (1,1,2,'20130131','20130121','Asignado')

INSERT INTO GD.FORMULARIO_EVALUACION_EMPLEADO
(CODIGO_FORMULARIO_EVALUACION,CODIGO_EMPLEADO,CODIGO_EVALUADOR,FECHA_VIGENCIA,FECHA_EVALUADO,ESTADO)
VALUES (1,3,2,'20130131','20130121','Asignado')

-- Ejecutar luego de crear el formulario
INSERT INTO GD.FORMULARIO_EVALUACION_CALIFICACION VALUES (2,1,1,1)
INSERT INTO GD.FORMULARIO_EVALUACION_CALIFICACION VALUES (2,1,1,2)
INSERT INTO GD.FORMULARIO_EVALUACION_CALIFICACION VALUES (2,1,2,10)
INSERT INTO GD.FORMULARIO_EVALUACION_CALIFICACION VALUES (2,1,3,12)

INSERT INTO GD.FORMULARIO_EVALUACION_EMPLEADO
(CODIGO_FORMULARIO_EVALUACION,CODIGO_EMPLEADO,CODIGO_EVALUADOR,FECHA_VIGENCIA,FECHA_EVALUADO,ESTADO)
VALUES (2,3,2,'20130131','20130121','Asignado')
