USE [master]
GO
/****** Object:  Database [TMD]    Script Date: 01/04/2013 21:07:10 ******/
CREATE DATABASE [TMD] ON  PRIMARY 
( NAME = N'TMD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.LSQLSERV7_R2\MSSQL\DATA\TMD.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TMD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.LSQLSERV7_R2\MSSQL\DATA\TMD_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [TMD] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TMD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TMD] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [TMD] SET ANSI_NULLS OFF
GO
ALTER DATABASE [TMD] SET ANSI_PADDING OFF
GO
ALTER DATABASE [TMD] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [TMD] SET ARITHABORT OFF
GO
ALTER DATABASE [TMD] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [TMD] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [TMD] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [TMD] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [TMD] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [TMD] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [TMD] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [TMD] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [TMD] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [TMD] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [TMD] SET  DISABLE_BROKER
GO
ALTER DATABASE [TMD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [TMD] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [TMD] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [TMD] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [TMD] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [TMD] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [TMD] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [TMD] SET  READ_WRITE
GO
ALTER DATABASE [TMD] SET RECOVERY FULL
GO
ALTER DATABASE [TMD] SET  MULTI_USER
GO
ALTER DATABASE [TMD] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [TMD] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'TMD', N'ON'
GO
USE [TMD]
GO
/****** Object:  Schema [GEN]    Script Date: 01/04/2013 21:07:10 ******/
CREATE SCHEMA [GEN] AUTHORIZATION [dbo]
GO
/****** Object:  Schema [GD]    Script Date: 01/04/2013 21:07:10 ******/
CREATE SCHEMA [GD] AUTHORIZATION [dbo]
GO
/****** Object:  Table [GD].[FORMULARIO_EVALUACION]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[FORMULARIO_EVALUACION](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[NOMBRE] [varchar](60) NOT NULL,
	[FECHA_ASIGNACION] [datetime] NULL,
	[ESTADO] [varchar](20) NULL,
 CONSTRAINT [PK_FORMULARIO_EVALUACION] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[FORMACION_ACADEMICA]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[FORMACION_ACADEMICA](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[INDICADOR_CERTIFICACION_TECNICA] [bit] NULL,
	[NOMBRE_NIVEL] [varchar](50) NULL,
 CONSTRAINT [PK_FORMACION_ACADEMICA] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[SECCION]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[SECCION](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](50) NULL,
 CONSTRAINT [PK_SECCION] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GEN].[ROL]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GEN].[ROL](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](30) NULL,
 CONSTRAINT [PK_ROL] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[TIPO_MERECIMIENTO_EVALUACION]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[TIPO_MERECIMIENTO_EVALUACION](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](20) NULL,
 CONSTRAINT [PK_TIPO_MERECIMIENTO] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[TIPO_CALIFICACION_EVALUACION]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[TIPO_CALIFICACION_EVALUACION](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](20) NULL,
 CONSTRAINT [PK_TIPO_CALIFICACION] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[AREA]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[AREA](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](30) NULL,
 CONSTRAINT [PK_AREA] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[PLAN_DESARROLLO]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[PLAN_DESARROLLO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[FECHA_PLAN] [datetime] NOT NULL,
	[FECHA_INICIO] [datetime] NULL,
	[FECHA_FIN] [datetime] NULL,
	[OBJETIVO] [varchar](200) NULL,
	[PASO] [varchar](200) NULL,
	[INDICADOR_ENVIO] [bit] NULL,
	[FECHA_ENVIO] [datetime] NULL,
 CONSTRAINT [PK_PLAN_DESARROLLO] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[PROYECTO]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[PROYECTO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](50) NULL,
	[FECHA_INICIO] [datetime] NULL,
	[FECHA_FIN] [datetime] NULL,
 CONSTRAINT [PK_PROYECTO] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[POSTULANTE]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[POSTULANTE](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRES] [varchar](50) NULL,
	[APELLIDO_PATERNO] [varchar](50) NULL,
	[APELLIDO_MATERNO] [varchar](50) NULL,
	[TIPO_POSTULANTE] [varchar](255) NULL,
	[FECHA_NACIMIENTO] [datetime] NULL,
	[ESTADO_CIVIL] [varchar](20) NULL,
	[PRETENCION_SALARIAL] [float] NULL,
	[DIRECCION] [varchar](100) NULL,
	[PROVINCIA] [varchar](50) NULL,
	[DEPARTAMENTO] [varchar](50) NULL,
	[DISTRITO] [varchar](50) NULL,
	[NACIONALIDAD] [varchar](50) NULL,
	[GENERO] [varchar](20) NULL,
	[TELEFONO] [varchar](15) NULL,
	[CELULAR] [int] NULL,
	[EMAIL] [varchar](20) NULL,
	[INDICADOR_APROBACION] [bit] NULL,
	[CODIGO_REQUERIMIENTO] [int] NOT NULL,
 CONSTRAINT [PK_POSTULANTE] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[PLAN_DESARROLLO_DETALLE]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[PLAN_DESARROLLO_DETALLE](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_PLAN_DESARROLLO] [int] NOT NULL,
	[FECHA_INICIO] [datetime] NULL,
	[FECHA_FIN] [datetime] NULL,
	[DESCRIPCION] [varchar](100) NULL,
 CONSTRAINT [PK_PLAN_DESARROLLO_DETALLE] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC,
	[CODIGO_PLAN_DESARROLLO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[COMPETENCIA_INDICADOR]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[COMPETENCIA_INDICADOR](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_TIPO_CALIFICACION_EVALUACION] [int] NOT NULL,
	[DESCRIPCION] [varchar](50) NULL,
 CONSTRAINT [PK_COMPETENCIA_INDICADOR] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC,
	[CODIGO_TIPO_CALIFICACION_EVALUACION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[SECCION_DETALLE]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[SECCION_DETALLE](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_SECCION] [int] NOT NULL,
	[DESCRIPCION] [varchar](50) NULL,
 CONSTRAINT [PK_SECCION_DETALLE] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC,
	[CODIGO_SECCION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[EXAMEN]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[EXAMEN](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[TITULO_EXAMEN] [varchar](100) NULL,
	[RESULTADO_EXAMEN] [int] NULL,
	[OBSERVACION_EXAMEN] [varchar](255) NULL,
	[CODIGO_POSTULANTE] [int] NOT NULL,
 CONSTRAINT [PK_EXAMEN] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[ENTREVISTA]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[ENTREVISTA](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[TITULO_ENTREVISTA] [varchar](100) NULL,
	[RESULTADO_ENTREVISTA] [varchar](255) NULL,
	[OBSERVACION_ENTREVISTA] [varchar](255) NULL,
	[CODIGO_POSTULANTE] [int] NOT NULL,
 CONSTRAINT [PK_ENTREVISTA] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[EMPLEADO]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[EMPLEADO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_AREA] [int] NOT NULL,
	[APELLIDO_PATERNO] [varchar](30) NULL,
	[APELLIDO_MATERNO] [varchar](30) NULL,
	[NOMBRES] [varchar](30) NULL,
	[ESTADO] [varchar](20) NULL,
	[CODIGO_JEFE] [int] NULL,
 CONSTRAINT [PK_EMPLEADO_1] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[PROYECTO_ROL]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [GD].[PROYECTO_ROL](
	[CODIGO_PROYECTO] [int] NOT NULL,
	[CODIGO_ROL] [int] NOT NULL,
	[PRINCIPAL] [int] NULL,
 CONSTRAINT [PK_PROYECTO_ROL] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO_PROYECTO] ASC,
	[CODIGO_ROL] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [GD].[RANGO_MERECIMIENTO]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[RANGO_MERECIMIENTO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_TIPO_MERECIMIENTO_EVALUACION] [int] NOT NULL,
	[VALOR_MINIMO] [int] NULL,
	[VALOR_MAXIMO] [int] NULL,
	[DESCRIPCION] [varbinary](100) NULL,
 CONSTRAINT [PK_RANGO_MERECIMIENTO] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC,
	[CODIGO_TIPO_MERECIMIENTO_EVALUACION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[PROYECTO_ROL_EMPLEADO]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [GD].[PROYECTO_ROL_EMPLEADO](
	[CODIGO_EMPLEADO] [int] NOT NULL,
	[CODIGO_ROL] [int] NOT NULL,
	[CODIGO_PROYECTO] [int] NOT NULL,
 CONSTRAINT [PK_PROYECTO_ROL_EMPLEADO] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO_EMPLEADO] ASC,
	[CODIGO_ROL] ASC,
	[CODIGO_PROYECTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [GD].[COMPETENCIA_INDICADOR_DETALLE]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[COMPETENCIA_INDICADOR_DETALLE](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_COMPETENCIA_INDICADOR] [int] NOT NULL,
	[CODIGO_TIPO_CALIFICACION_EVALUACION] [int] NOT NULL,
	[DESCRIPCION] [varchar](50) NULL,
	[NIVEL_1] [varchar](100) NULL,
	[NIVEL_2] [varchar](100) NULL,
	[NIVEL_3] [varchar](100) NULL,
	[NIVEL_4] [varchar](100) NULL,
	[NIVEL_5] [varchar](100) NULL,
 CONSTRAINT [PK_COMPETENCIA_INDICADOR_DETALLE] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC,
	[CODIGO_COMPETENCIA_INDICADOR] ASC,
	[CODIGO_TIPO_CALIFICACION_EVALUACION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[FORMULARIO_EVALUACION_EMPLEADO]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO](
	[CODIGO_FORMULARIO_EVALUACION] [int] NOT NULL,
	[CODIGO_EMPLEADO] [int] NOT NULL,
	[CODIGO_EVALUADOR] [int] NOT NULL,
	[FECHA_VIGENCIA] [datetime] NULL,
	[FECHA_EVALUADO] [datetime] NULL,
	[FECHA_EVALUADOR] [datetime] NULL,
	[RESULTADO] [int] NULL,
	[ESTADO] [varchar](20) NULL,
	[CODIGO_PLAN_DESARROLLO_DETALLE] [int] NULL,
	[CODIGO_PLAN_DESARROLLO] [int] NULL,
	[CODIGO_RANGO_MERECIMIENTO] [int] NULL,
	[CODIGO_TIPO_MERECIMIENTO_EVALUACION] [int] NULL,
 CONSTRAINT [PK_FORMULARIO_EVALUACION_EMPLEADO] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO_FORMULARIO_EVALUACION] ASC,
	[CODIGO_EMPLEADO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[FORMULARIO_EVALUACION_SECCION]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [GD].[FORMULARIO_EVALUACION_SECCION](
	[CODIGO_FORMULARIO_EVALUACION] [int] NOT NULL,
	[CODIGO_SECCION] [int] NOT NULL,
	[CODIGO_SECCION_DETALLE] [int] NOT NULL,
 CONSTRAINT [PK_FORMULARIO_EVALUACION_SECCION] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO_FORMULARIO_EVALUACION] ASC,
	[CODIGO_SECCION] ASC,
	[CODIGO_SECCION_DETALLE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [GD].[REQUERIMIENTO]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[REQUERIMIENTO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[FECHA_INICIO] [datetime] NULL,
	[FECHA_LIMITE] [datetime] NULL,
	[GENERO] [varchar](255) NULL,
	[NACIONALIDAD] [varchar](255) NULL,
	[EDAD_MINIMA] [int] NULL,
	[EDAD_MAXIMA] [int] NULL,
	[RENUMERACION_EFECTIVA] [float] NULL,
	[ESTADO] [varchar](255) NULL,
	[NUMERO_PLAZA] [int] NULL,
	[CONOCIMIENTO] [varchar](255) NULL,
	[OBSERVACION] [varchar](255) NULL,
	[CODIGO_EMPLEADO] [int] NOT NULL,
	[CODIGO_FORMACION_ACADEMICA] [int] NOT NULL,
	[CODIGO_ROL] [int] NOT NULL,
 CONSTRAINT [PK_REQUERIMIENTO] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[IDIOMA_REQUERIMIENTO]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[IDIOMA_REQUERIMIENTO](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[PORCENTAJE_IDIOMA] [int] NULL,
	[NOMBRE_IDIOMA] [varchar](50) NULL,
	[CODIGO_REQUERIMIENTO] [int] NOT NULL,
 CONSTRAINT [PK_IDIOMA_REQUERIMIENTO] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[FORMULARIO_EVALUACION_EMPLEADO_SECCION]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO_SECCION](
	[CODIGO_FORMULARIO_EVALUACION] [int] NOT NULL,
	[CODIGO_EMPLEADO] [int] NOT NULL,
	[CODIGO_SECCION] [int] NOT NULL,
	[CODIGO_SECCION_DETALLE] [int] NOT NULL,
	[VALOR_SECCION] [varchar](200) NULL,
 CONSTRAINT [PK_FORMULARIO_EVALUACION_EMPLEADO_SECCION] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO_FORMULARIO_EVALUACION] ASC,
	[CODIGO_EMPLEADO] ASC,
	[CODIGO_SECCION] ASC,
	[CODIGO_SECCION_DETALLE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION](
	[CODIGO_FORMULARIO_EVALUACION] [int] NOT NULL,
	[CODIGO_EMPLEADO] [int] NOT NULL,
	[CODIGO_TIPO_CALIFICACION_EVALUACION] [int] NOT NULL,
	[CODIGO_COMPETENCIA_INDICADOR] [int] NOT NULL,
	[CODIGO_COMPETENCIA_INDICADOR_DETALLE] [int] NOT NULL,
	[VALOR_CALIFICACION] [varchar](200) NULL,
 CONSTRAINT [PK_FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO_FORMULARIO_EVALUACION] ASC,
	[CODIGO_EMPLEADO] ASC,
	[CODIGO_TIPO_CALIFICACION_EVALUACION] ASC,
	[CODIGO_COMPETENCIA_INDICADOR] ASC,
	[CODIGO_COMPETENCIA_INDICADOR_DETALLE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [GD].[FORMULARIO_EVALUACION_CALIFICACION]    Script Date: 01/04/2013 21:07:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [GD].[FORMULARIO_EVALUACION_CALIFICACION](
	[CODIGO_FORMULARIO_EVALUACION] [int] NOT NULL,
	[CODIGO_TIPO_CALIFICACION_EVALUACION] [int] NOT NULL,
	[CODIGO_COMPETENCIA_INDICADOR] [int] NOT NULL,
	[CODIGO_COMPETENCIA_INDICADOR_DETALLE] [int] NOT NULL,
 CONSTRAINT [PK_FORMULARIO_EVALUACION_CALIFICACION] PRIMARY KEY NONCLUSTERED 
(
	[CODIGO_FORMULARIO_EVALUACION] ASC,
	[CODIGO_TIPO_CALIFICACION_EVALUACION] ASC,
	[CODIGO_COMPETENCIA_INDICADOR] ASC,
	[CODIGO_COMPETENCIA_INDICADOR_DETALLE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [GD].[USP_FORMULARIO_EVALUACION_EMPLEADO_EVALUADO_UPD]    Script Date: 01/04/2013 21:07:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Eduardo Huapaya Flores>
-- Create date: <01/12/2012>
-- Description:	<Actualiza la fecha de la autoevaluación y el estado del formulario>
-- =============================================
CREATE PROCEDURE [GD].[USP_FORMULARIO_EVALUACION_EMPLEADO_EVALUADO_UPD]
	@CODIGO_FORMULARIO_EVALUACION INT,
	@CODIGO_EMPLEADO INT,
	@FECHA DATETIME
AS
BEGIN
	SET NOCOUNT ON
	
	UPDATE GD.FORMULARIO_EVALUACION_EMPLEADO
	SET 
	FECHA_EVALUADO = CONVERT(datetime,@FECHA,103),
	ESTADO = 'Registrado'
	WHERE
	CODIGO_FORMULARIO_EVALUACION = @CODIGO_FORMULARIO_EVALUACION AND
	CODIGO_EMPLEADO = @CODIGO_EMPLEADO
	
END
GO
/****** Object:  StoredProcedure [GD].[USP_FORMULARIO_EMPLEADO_SEL]    Script Date: 01/04/2013 21:07:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Eduardo Huapaya Flores>
-- Create date: <28/11/2012>
-- Description:	<Obtiene los datos del formulario de evaluación para cualquier empleado>
-- =============================================
CREATE PROCEDURE [GD].[USP_FORMULARIO_EMPLEADO_SEL]
(
	@CODIGO_EMPLEADO Int
)
AS
BEGIN
	SET NOCOUNT ON;

    -- Datos del formulario de evaluación
	SELECT FORMULARIO_EVALUACION_EMPLEADO.FECHA_EVALUADO,FORMULARIO_EVALUACION.NOMBRE,FORMULARIO_EVALUACION_EMPLEADO.ESTADO,
	(EMPLEADO.APELLIDO_PATERNO + SPACE(1) + EMPLEADO.APELLIDO_MATERNO + SPACE(1) + EMPLEADO.NOMBRES) AS EVALUADO,
	(EMPLEADOJ.APELLIDO_PATERNO + SPACE(1) + EMPLEADOJ.APELLIDO_MATERNO + SPACE(1) + EMPLEADOJ.NOMBRES) AS EVALUADOR,
	AREA.DESCRIPCION AS AREA,
	SECCION.CODIGO AS CODIGO_SECCION,SECCION.DESCRIPCION AS SECCION,SECCION_DETALLE.CODIGO AS CODIGO_SECCION_DETALLE,SECCION_DETALLE.DESCRIPCION AS SECCION_DETALLE,
	PROYECTO.DESCRIPCION AS PROYECTO, ROL.DESCRIPCION AS ROL
	FROM GD.FORMULARIO_EVALUACION_EMPLEADO
	JOIN GD.FORMULARIO_EVALUACION ON(FORMULARIO_EVALUACION.CODIGO=FORMULARIO_EVALUACION_EMPLEADO.CODIGO_FORMULARIO_EVALUACION)
	JOIN GD.EMPLEADO ON(EMPLEADO.CODIGO=FORMULARIO_EVALUACION_EMPLEADO.CODIGO_EMPLEADO)
	JOIN GD.EMPLEADO EMPLEADOJ ON(EMPLEADOJ.CODIGO=EMPLEADO.CODIGO_JEFE)
	JOIN GD.AREA ON(AREA.CODIGO=EMPLEADO.CODIGO_AREA)
	JOIN GD.PROYECTO_ROL_EMPLEADO ON(PROYECTO_ROL_EMPLEADO.CODIGO_EMPLEADO=FORMULARIO_EVALUACION_EMPLEADO.CODIGO_EMPLEADO)
	JOIN GD.PROYECTO ON(GD.PROYECTO.CODIGO=PROYECTO_ROL_EMPLEADO.CODIGO_PROYECTO)
	JOIN GEN.ROL ON(ROL.CODIGO=PROYECTO_ROL_EMPLEADO.CODIGO_ROL)
	JOIN GD.FORMULARIO_EVALUACION_SECCION ON
	(FORMULARIO_EVALUACION_SECCION.CODIGO_FORMULARIO_EVALUACION=FORMULARIO_EVALUACION_EMPLEADO.CODIGO_FORMULARIO_EVALUACION)
	JOIN GD.SECCION ON(SECCION.CODIGO=FORMULARIO_EVALUACION_SECCION.CODIGO_SECCION)
	JOIN GD.SECCION_DETALLE ON
	(SECCION_DETALLE.CODIGO=FORMULARIO_EVALUACION_SECCION.CODIGO_SECCION_DETALLE AND SECCION_DETALLE.CODIGO_SECCION=FORMULARIO_EVALUACION_SECCION.CODIGO_SECCION)
	WHERE 
	GD.FORMULARIO_EVALUACION_EMPLEADO.CODIGO_EMPLEADO=@CODIGO_EMPLEADO AND
	GD.FORMULARIO_EVALUACION_EMPLEADO.ESTADO='Asignado'
	ORDER BY SECCION_DETALLE.CODIGO
	
END
GO
/****** Object:  StoredProcedure [GD].[USP_FORMULARIO_EVALUACION_EMPLEADO_EVALUADOR_UPD]    Script Date: 01/04/2013 21:07:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Eduardo Huapaya Flores>
-- Create date: <01/12/2012>
-- Description:	<Actualiza la fecha de la evaluación y el estado del formulario>
-- =============================================
CREATE PROCEDURE [GD].[USP_FORMULARIO_EVALUACION_EMPLEADO_EVALUADOR_UPD]
	@CODIGO_FORMULARIO_EVALUACION INT,
	@CODIGO_EMPLEADO INT,
	@FECHA DATETIME
AS
BEGIN
	SET NOCOUNT ON
	
	UPDATE GD.FORMULARIO_EVALUACION_EMPLEADO
	SET 
	FECHA_EVALUADOR = CONVERT(datetime,@FECHA,103),
	ESTADO = 'Evaluado'
	WHERE
	CODIGO_FORMULARIO_EVALUACION = @CODIGO_FORMULARIO_EVALUACION AND
	CODIGO_EMPLEADO = @CODIGO_EMPLEADO
	
END
GO
/****** Object:  StoredProcedure [GD].[USP_FORMULARIO_EVALUACION_EMPLEADO_SECCION_INS]    Script Date: 01/04/2013 21:07:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Eduardo Huapaya Flores>
-- Create date: <01/12/2012>
-- Description:	<Guarda la información de la autoevaluación>
-- =============================================
CREATE PROCEDURE [GD].[USP_FORMULARIO_EVALUACION_EMPLEADO_SECCION_INS]
	@CODIGO_FORMULARIO_EVALUACION INT,
	@CODIGO_EMPLEADO INT,
	@CODIGO_SECCION INT,
	@CODIGO_SECCION_DETALLE INT,
	@VALOR_SECCION VARCHAR(200)
AS 
BEGIN 
     SET NOCOUNT ON 
     
     INSERT INTO GD.FORMULARIO_EVALUACION_EMPLEADO_SECCION
     VALUES ( 
       @CODIGO_FORMULARIO_EVALUACION,
       @CODIGO_EMPLEADO,
       @CODIGO_SECCION ,
       @CODIGO_SECCION_DETALLE,
       @VALOR_SECCION
          ) 
     
END
GO
/****** Object:  StoredProcedure [GD].[USP_FORMULARIO_EVALUACION_EMPLEADO_EVALUADOR1_SEL]    Script Date: 01/04/2013 21:07:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Eduardo Huapaya Flores>
-- Create date: <03/12/2012>
-- Description:	<Obtiene las competencias del formulario de evaluación del empleado>
-- =============================================
CREATE PROCEDURE [GD].[USP_FORMULARIO_EVALUACION_EMPLEADO_EVALUADOR1_SEL]
(
	@CODIGO_EVALUADOR Int
)
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
	CIN.CODIGO,CIN.DESCRIPCION AS COMPETENCIA,
	CID.CODIGO,CID.DESCRIPCION AS COMPETENCIA_DETALLE,
	FEEC.VALOR_CALIFICACION AS DATO_CALIFICACION
	FROM GD.FORMULARIO_EVALUACION_EMPLEADO FEE
	JOIN GD.FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION FEEC ON
	(FEEC.CODIGO_FORMULARIO_EVALUACION=FEE.CODIGO_FORMULARIO_EVALUACION AND	FEEC.CODIGO_EMPLEADO=FEE.CODIGO_EMPLEADO)
	JOIN GD.COMPETENCIA_INDICADOR CIN ON
	(CIN.CODIGO=FEEC.CODIGO_COMPETENCIA_INDICADOR)
	JOIN GD.COMPETENCIA_INDICADOR_DETALLE CID ON
	(CID.CODIGO=FEEC.CODIGO_COMPETENCIA_INDICADOR_DETALLE AND CID.CODIGO_COMPETENCIA_INDICADOR=FEEC.CODIGO_COMPETENCIA_INDICADOR)
	WHERE 
	FEE.CODIGO_EVALUADOR=@CODIGO_EVALUADOR AND
	FEE.ESTADO='Registrado'
	ORDER BY CID.CODIGO
	
END
GO
/****** Object:  StoredProcedure [GD].[USP_FORMULARIO_EVALUACION_EMPLEADO_EVALUADOR_SEL]    Script Date: 01/04/2013 21:07:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Eduardo Huapaya Flores>
-- Create date: <03/12/2012>
-- Description:	<Obtiene los datos del formulario de evaluación registrado por el empleado>
-- =============================================
CREATE PROCEDURE [GD].[USP_FORMULARIO_EVALUACION_EMPLEADO_EVALUADOR_SEL]
(
	@CODIGO_EVALUADOR Int
)
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT FEE.FECHA_EVALUADO,FEE.ESTADO,
	(EMPLEADO.APELLIDO_PATERNO + SPACE(1) + EMPLEADO.APELLIDO_MATERNO + SPACE(1) + EMPLEADO.NOMBRES) AS EVALUADO,
	(EMPLEADOJ.APELLIDO_PATERNO + SPACE(1) + EMPLEADOJ.APELLIDO_MATERNO + SPACE(1) + EMPLEADOJ.NOMBRES) AS EVALUADOR,
	AREA.DESCRIPCION AS AREA,
	SECCION.CODIGO AS CODIGO_SECCION,SECCION.DESCRIPCION AS SECCION,SECCION_DETALLE.CODIGO AS CODIGO_SECCION_DETALLE,SECCION_DETALLE.DESCRIPCION AS SECCION_DETALLE,
	PROYECTO.DESCRIPCION AS PROYECTO, ROL.DESCRIPCION AS ROL,
	FEES.VALOR_SECCION AS DATO_SECCION,
	NOMBRE=(SELECT NOMBRE FROM GD.FORMULARIO_EVALUACION WHERE GD.FORMULARIO_EVALUACION.CODIGO=FEE.CODIGO_FORMULARIO_EVALUACION)
	FROM GD.FORMULARIO_EVALUACION_EMPLEADO FEE
	JOIN GD.FORMULARIO_EVALUACION_EMPLEADO_SECCION FEES ON
	(FEES.CODIGO_FORMULARIO_EVALUACION=FEE.CODIGO_FORMULARIO_EVALUACION AND 
	FEES.CODIGO_EMPLEADO=FEE.CODIGO_EMPLEADO)
	JOIN GD.EMPLEADO ON(EMPLEADO.CODIGO=FEE.CODIGO_EMPLEADO)
	JOIN GD.EMPLEADO EMPLEADOJ ON(EMPLEADOJ.CODIGO=EMPLEADO.CODIGO_JEFE)
	JOIN GD.AREA ON(AREA.CODIGO=EMPLEADO.CODIGO_AREA)
	JOIN GD.PROYECTO_ROL_EMPLEADO ON(PROYECTO_ROL_EMPLEADO.CODIGO_EMPLEADO=FEE.CODIGO_EMPLEADO)
	JOIN GD.PROYECTO ON(GD.PROYECTO.CODIGO=PROYECTO_ROL_EMPLEADO.CODIGO_PROYECTO)
	JOIN GEN.ROL ON(ROL.CODIGO=PROYECTO_ROL_EMPLEADO.CODIGO_ROL)
	JOIN GD.SECCION ON(SECCION.CODIGO=FEES.CODIGO_SECCION)
	JOIN GD.SECCION_DETALLE ON
	(SECCION_DETALLE.CODIGO=FEES.CODIGO_SECCION_DETALLE AND SECCION_DETALLE.CODIGO_SECCION=FEES.CODIGO_SECCION)
	WHERE 
	FEE.CODIGO_EVALUADOR=@CODIGO_EVALUADOR AND
	FEE.ESTADO='Registrado'
	ORDER BY SECCION_DETALLE.CODIGO

END
GO
/****** Object:  StoredProcedure [GD].[USP_FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION_INS]    Script Date: 01/04/2013 21:07:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Eduardo Huapaya Flores>
-- Create date: <01/12/2012>
-- Description:	<Guarda la información de la evaluación>
-- =============================================
CREATE PROCEDURE [GD].[USP_FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION_INS]
	@CODIGO_FORMULARIO_EVALUACION INT,
	@CODIGO_EMPLEADO INT,
	@CODIGO_TIPO_CALIFICACION_EVALUACION INT,
	@CODIGO_COMPETENCIA_INDICADOR INT,
	@CODIGO_COMPETENCIA_INDICADOR_DETALLE INT,
	@VALOR_CALIFICACION VARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON 
     
     INSERT INTO GD.FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION
     VALUES ( 
       @CODIGO_FORMULARIO_EVALUACION,
       @CODIGO_EMPLEADO,
       @CODIGO_TIPO_CALIFICACION_EVALUACION,
       @CODIGO_COMPETENCIA_INDICADOR,
       @CODIGO_COMPETENCIA_INDICADOR_DETALLE,
       @VALOR_CALIFICACION
          ) 

END
GO
/****** Object:  ForeignKey [FK_PLAN_DESARROLLO_DETALLE_PLAN_DESARROLLO]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[PLAN_DESARROLLO_DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_PLAN_DESARROLLO_DETALLE_PLAN_DESARROLLO] FOREIGN KEY([CODIGO_PLAN_DESARROLLO])
REFERENCES [GD].[PLAN_DESARROLLO] ([CODIGO])
GO
ALTER TABLE [GD].[PLAN_DESARROLLO_DETALLE] CHECK CONSTRAINT [FK_PLAN_DESARROLLO_DETALLE_PLAN_DESARROLLO]
GO
/****** Object:  ForeignKey [FK_COMPETENCIA_INDICADOR_TIPO_CALIFICACION]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[COMPETENCIA_INDICADOR]  WITH CHECK ADD  CONSTRAINT [FK_COMPETENCIA_INDICADOR_TIPO_CALIFICACION] FOREIGN KEY([CODIGO_TIPO_CALIFICACION_EVALUACION])
REFERENCES [GD].[TIPO_CALIFICACION_EVALUACION] ([CODIGO])
GO
ALTER TABLE [GD].[COMPETENCIA_INDICADOR] CHECK CONSTRAINT [FK_COMPETENCIA_INDICADOR_TIPO_CALIFICACION]
GO
/****** Object:  ForeignKey [FK_SECCION_DETALLE_SECCION]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[SECCION_DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_SECCION_DETALLE_SECCION] FOREIGN KEY([CODIGO_SECCION])
REFERENCES [GD].[SECCION] ([CODIGO])
GO
ALTER TABLE [GD].[SECCION_DETALLE] CHECK CONSTRAINT [FK_SECCION_DETALLE_SECCION]
GO
/****** Object:  ForeignKey [FK_EXAMEN]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[EXAMEN]  WITH CHECK ADD  CONSTRAINT [FK_EXAMEN] FOREIGN KEY([CODIGO_POSTULANTE])
REFERENCES [GD].[POSTULANTE] ([CODIGO])
GO
ALTER TABLE [GD].[EXAMEN] CHECK CONSTRAINT [FK_EXAMEN]
GO
/****** Object:  ForeignKey [FK_ENTREVISTA]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[ENTREVISTA]  WITH CHECK ADD  CONSTRAINT [FK_ENTREVISTA] FOREIGN KEY([CODIGO_POSTULANTE])
REFERENCES [GD].[POSTULANTE] ([CODIGO])
GO
ALTER TABLE [GD].[ENTREVISTA] CHECK CONSTRAINT [FK_ENTREVISTA]
GO
/****** Object:  ForeignKey [FK_EMPLEADO_AREA]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADO_AREA] FOREIGN KEY([CODIGO_AREA])
REFERENCES [GD].[AREA] ([CODIGO])
GO
ALTER TABLE [GD].[EMPLEADO] CHECK CONSTRAINT [FK_EMPLEADO_AREA]
GO
/****** Object:  ForeignKey [FK_PROYECTO_ROL_PROYECTO]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[PROYECTO_ROL]  WITH CHECK ADD  CONSTRAINT [FK_PROYECTO_ROL_PROYECTO] FOREIGN KEY([CODIGO_PROYECTO])
REFERENCES [GD].[PROYECTO] ([CODIGO])
GO
ALTER TABLE [GD].[PROYECTO_ROL] CHECK CONSTRAINT [FK_PROYECTO_ROL_PROYECTO]
GO
/****** Object:  ForeignKey [FK_PROYECTO_ROL_ROL]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[PROYECTO_ROL]  WITH CHECK ADD  CONSTRAINT [FK_PROYECTO_ROL_ROL] FOREIGN KEY([CODIGO_ROL])
REFERENCES [GEN].[ROL] ([CODIGO])
GO
ALTER TABLE [GD].[PROYECTO_ROL] CHECK CONSTRAINT [FK_PROYECTO_ROL_ROL]
GO
/****** Object:  ForeignKey [FK_RANGO_MERECIMIENTO_TIPO_MERECIMIENTO_EVALUACION]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[RANGO_MERECIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_RANGO_MERECIMIENTO_TIPO_MERECIMIENTO_EVALUACION] FOREIGN KEY([CODIGO_TIPO_MERECIMIENTO_EVALUACION])
REFERENCES [GD].[TIPO_MERECIMIENTO_EVALUACION] ([CODIGO])
GO
ALTER TABLE [GD].[RANGO_MERECIMIENTO] CHECK CONSTRAINT [FK_RANGO_MERECIMIENTO_TIPO_MERECIMIENTO_EVALUACION]
GO
/****** Object:  ForeignKey [FK_PROYECTO_ROL_EMPLEADO_EMPLEADO]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[PROYECTO_ROL_EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_PROYECTO_ROL_EMPLEADO_EMPLEADO] FOREIGN KEY([CODIGO_EMPLEADO])
REFERENCES [GD].[EMPLEADO] ([CODIGO])
GO
ALTER TABLE [GD].[PROYECTO_ROL_EMPLEADO] CHECK CONSTRAINT [FK_PROYECTO_ROL_EMPLEADO_EMPLEADO]
GO
/****** Object:  ForeignKey [FK_PROYECTO_ROL_EMPLEADO_PROYECTO_ROL]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[PROYECTO_ROL_EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_PROYECTO_ROL_EMPLEADO_PROYECTO_ROL] FOREIGN KEY([CODIGO_PROYECTO], [CODIGO_ROL])
REFERENCES [GD].[PROYECTO_ROL] ([CODIGO_PROYECTO], [CODIGO_ROL])
GO
ALTER TABLE [GD].[PROYECTO_ROL_EMPLEADO] CHECK CONSTRAINT [FK_PROYECTO_ROL_EMPLEADO_PROYECTO_ROL]
GO
/****** Object:  ForeignKey [FK_COMPETENCIA_INDICADOR_DETALLE_COMPETENCIA_INDICADOR]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[COMPETENCIA_INDICADOR_DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_COMPETENCIA_INDICADOR_DETALLE_COMPETENCIA_INDICADOR] FOREIGN KEY([CODIGO_COMPETENCIA_INDICADOR], [CODIGO_TIPO_CALIFICACION_EVALUACION])
REFERENCES [GD].[COMPETENCIA_INDICADOR] ([CODIGO], [CODIGO_TIPO_CALIFICACION_EVALUACION])
GO
ALTER TABLE [GD].[COMPETENCIA_INDICADOR_DETALLE] CHECK CONSTRAINT [FK_COMPETENCIA_INDICADOR_DETALLE_COMPETENCIA_INDICADOR]
GO
/****** Object:  ForeignKey [FK_FORMULARIO_EVALUACION_EMPLEADO_EMPLEADO]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_EMPLEADO] FOREIGN KEY([CODIGO_EMPLEADO])
REFERENCES [GD].[EMPLEADO] ([CODIGO])
GO
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO] CHECK CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_EMPLEADO]
GO
/****** Object:  ForeignKey [FK_FORMULARIO_EVALUACION_EMPLEADO_FORMULARIO_EVALUACION]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_FORMULARIO_EVALUACION] FOREIGN KEY([CODIGO_FORMULARIO_EVALUACION])
REFERENCES [GD].[FORMULARIO_EVALUACION] ([CODIGO])
GO
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO] CHECK CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_FORMULARIO_EVALUACION]
GO
/****** Object:  ForeignKey [FK_FORMULARIO_EVALUACION_EMPLEADO_PLAN_DESARROLLO_DETALLE]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_PLAN_DESARROLLO_DETALLE] FOREIGN KEY([CODIGO_PLAN_DESARROLLO_DETALLE], [CODIGO_PLAN_DESARROLLO])
REFERENCES [GD].[PLAN_DESARROLLO_DETALLE] ([CODIGO], [CODIGO_PLAN_DESARROLLO])
GO
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO] CHECK CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_PLAN_DESARROLLO_DETALLE]
GO
/****** Object:  ForeignKey [FK_FORMULARIO_EVALUACION_EMPLEADO_RANGO_MERECIMIENTO]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_RANGO_MERECIMIENTO] FOREIGN KEY([CODIGO_RANGO_MERECIMIENTO], [CODIGO_TIPO_MERECIMIENTO_EVALUACION])
REFERENCES [GD].[RANGO_MERECIMIENTO] ([CODIGO], [CODIGO_TIPO_MERECIMIENTO_EVALUACION])
GO
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO] CHECK CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_RANGO_MERECIMIENTO]
GO
/****** Object:  ForeignKey [FK_FORMULARIO_EVALUACION_SECCION_FORMULARIO_EVALUACION]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[FORMULARIO_EVALUACION_SECCION]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO_EVALUACION_SECCION_FORMULARIO_EVALUACION] FOREIGN KEY([CODIGO_FORMULARIO_EVALUACION])
REFERENCES [GD].[FORMULARIO_EVALUACION] ([CODIGO])
GO
ALTER TABLE [GD].[FORMULARIO_EVALUACION_SECCION] CHECK CONSTRAINT [FK_FORMULARIO_EVALUACION_SECCION_FORMULARIO_EVALUACION]
GO
/****** Object:  ForeignKey [FK_FORMULARIO_EVALUACION_SECCION_SECCION_DETALLE]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[FORMULARIO_EVALUACION_SECCION]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO_EVALUACION_SECCION_SECCION_DETALLE] FOREIGN KEY([CODIGO_SECCION_DETALLE], [CODIGO_SECCION])
REFERENCES [GD].[SECCION_DETALLE] ([CODIGO], [CODIGO_SECCION])
GO
ALTER TABLE [GD].[FORMULARIO_EVALUACION_SECCION] CHECK CONSTRAINT [FK_FORMULARIO_EVALUACION_SECCION_SECCION_DETALLE]
GO
/****** Object:  ForeignKey [FK_REQUERIMIENTO_EMPLEADO]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[REQUERIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_REQUERIMIENTO_EMPLEADO] FOREIGN KEY([CODIGO_EMPLEADO])
REFERENCES [GD].[EMPLEADO] ([CODIGO])
GO
ALTER TABLE [GD].[REQUERIMIENTO] CHECK CONSTRAINT [FK_REQUERIMIENTO_EMPLEADO]
GO
/****** Object:  ForeignKey [FK_REQUERIMIENTO_FORMACION_ACADEMICA]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[REQUERIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_REQUERIMIENTO_FORMACION_ACADEMICA] FOREIGN KEY([CODIGO_FORMACION_ACADEMICA])
REFERENCES [GD].[FORMACION_ACADEMICA] ([CODIGO])
GO
ALTER TABLE [GD].[REQUERIMIENTO] CHECK CONSTRAINT [FK_REQUERIMIENTO_FORMACION_ACADEMICA]
GO
/****** Object:  ForeignKey [FK_REQUERIMIENTO_ROL]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[REQUERIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_REQUERIMIENTO_ROL] FOREIGN KEY([CODIGO_ROL])
REFERENCES [GEN].[ROL] ([CODIGO])
GO
ALTER TABLE [GD].[REQUERIMIENTO] CHECK CONSTRAINT [FK_REQUERIMIENTO_ROL]
GO
/****** Object:  ForeignKey [FK_IDIOMA_REQUERIMIENTO]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[IDIOMA_REQUERIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_IDIOMA_REQUERIMIENTO] FOREIGN KEY([CODIGO_REQUERIMIENTO])
REFERENCES [GD].[REQUERIMIENTO] ([CODIGO])
GO
ALTER TABLE [GD].[IDIOMA_REQUERIMIENTO] CHECK CONSTRAINT [FK_IDIOMA_REQUERIMIENTO]
GO
/****** Object:  ForeignKey [FK_FORMULARIO_EVALUACION_EMPLEADO_SECCION_FORMULARIO_EVALUACION_EMPLEADO]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO_SECCION]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_SECCION_FORMULARIO_EVALUACION_EMPLEADO] FOREIGN KEY([CODIGO_FORMULARIO_EVALUACION], [CODIGO_EMPLEADO])
REFERENCES [GD].[FORMULARIO_EVALUACION_EMPLEADO] ([CODIGO_FORMULARIO_EVALUACION], [CODIGO_EMPLEADO])
GO
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO_SECCION] CHECK CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_SECCION_FORMULARIO_EVALUACION_EMPLEADO]
GO
/****** Object:  ForeignKey [FK_FORMULARIO_EVALUACION_EMPLEADO_SECCION_SECCION_DETALLE]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO_SECCION]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_SECCION_SECCION_DETALLE] FOREIGN KEY([CODIGO_SECCION_DETALLE], [CODIGO_SECCION])
REFERENCES [GD].[SECCION_DETALLE] ([CODIGO], [CODIGO_SECCION])
GO
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO_SECCION] CHECK CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_SECCION_SECCION_DETALLE]
GO
/****** Object:  ForeignKey [FK_FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION_COMPETENCIA_INDICADOR_DETALLE]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION_COMPETENCIA_INDICADOR_DETALLE] FOREIGN KEY([CODIGO_COMPETENCIA_INDICADOR_DETALLE], [CODIGO_COMPETENCIA_INDICADOR], [CODIGO_TIPO_CALIFICACION_EVALUACION])
REFERENCES [GD].[COMPETENCIA_INDICADOR_DETALLE] ([CODIGO], [CODIGO_COMPETENCIA_INDICADOR], [CODIGO_TIPO_CALIFICACION_EVALUACION])
GO
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION] CHECK CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION_COMPETENCIA_INDICADOR_DETALLE]
GO
/****** Object:  ForeignKey [FK_FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION_FORMULARIO_EVALUACION_EMPLEADO]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION_FORMULARIO_EVALUACION_EMPLEADO] FOREIGN KEY([CODIGO_FORMULARIO_EVALUACION], [CODIGO_EMPLEADO])
REFERENCES [GD].[FORMULARIO_EVALUACION_EMPLEADO] ([CODIGO_FORMULARIO_EVALUACION], [CODIGO_EMPLEADO])
GO
ALTER TABLE [GD].[FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION] CHECK CONSTRAINT [FK_FORMULARIO_EVALUACION_EMPLEADO_CALIFICACION_FORMULARIO_EVALUACION_EMPLEADO]
GO
/****** Object:  ForeignKey [FK_FORMULARIO_EVALUACION_CALIFICACION_COMPETENCIA_INDICADOR_DETALLE]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[FORMULARIO_EVALUACION_CALIFICACION]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO_EVALUACION_CALIFICACION_COMPETENCIA_INDICADOR_DETALLE] FOREIGN KEY([CODIGO_COMPETENCIA_INDICADOR_DETALLE], [CODIGO_COMPETENCIA_INDICADOR], [CODIGO_TIPO_CALIFICACION_EVALUACION])
REFERENCES [GD].[COMPETENCIA_INDICADOR_DETALLE] ([CODIGO], [CODIGO_COMPETENCIA_INDICADOR], [CODIGO_TIPO_CALIFICACION_EVALUACION])
GO
ALTER TABLE [GD].[FORMULARIO_EVALUACION_CALIFICACION] CHECK CONSTRAINT [FK_FORMULARIO_EVALUACION_CALIFICACION_COMPETENCIA_INDICADOR_DETALLE]
GO
/****** Object:  ForeignKey [FK_FORMULARIO_EVALUACION_CALIFICACION_FORMULARIO_EVALUACION]    Script Date: 01/04/2013 21:07:12 ******/
ALTER TABLE [GD].[FORMULARIO_EVALUACION_CALIFICACION]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO_EVALUACION_CALIFICACION_FORMULARIO_EVALUACION] FOREIGN KEY([CODIGO_FORMULARIO_EVALUACION])
REFERENCES [GD].[FORMULARIO_EVALUACION] ([CODIGO])
GO
ALTER TABLE [GD].[FORMULARIO_EVALUACION_CALIFICACION] CHECK CONSTRAINT [FK_FORMULARIO_EVALUACION_CALIFICACION_FORMULARIO_EVALUACION]
GO
