USE TMD;

INSERT INTO GEN.PERSONA (NOMBRE_PERSONA, APELLIDO_PATERNO, APELLIDO_MATERNO, ESTADO)
VALUES ('ENRIQUE', 'OROSCO' , 'OSORES', 'A')

INSERT INTO GEN.PERSONA (NOMBRE_PERSONA, APELLIDO_PATERNO, APELLIDO_MATERNO, ESTADO)
VALUES ('MIGUEL', 'ZAPATA' , 'ROJAS', 'A')

INSERT INTO GEN.PERSONA (NOMBRE_PERSONA, APELLIDO_PATERNO, APELLIDO_MATERNO, ESTADO)
VALUES ('EVACHO', 'CONDEZO' , 'CAMARGO', 'A')

INSERT INTO GEN.PERSONA (NOMBRE_PERSONA, APELLIDO_PATERNO, APELLIDO_MATERNO, ESTADO)
VALUES ('JUAN', 'RIVAS' , 'SANCHEZ', 'A')

INSERT INTO GEN.PERSONA (NOMBRE_PERSONA, APELLIDO_PATERNO, APELLIDO_MATERNO, ESTADO)
VALUES ('WENDY', 'CAMARENA' , 'MALAGA', 'A')

INSERT INTO GEN.PERFIL_USUARIO(CODIGO, DESCRIPCION)
VALUES ('0000000001', 'ASESOR DE VENTA' )

--	SELECT * FROM GEN.PERSONA
INSERT INTO GEN.USUARIO (CODIGO_PERSONA, CODIGO_USUARIO, CONTRASENIA, ESTADO, CODIGO_PERFIL_USUARIO)
VALUES (1, 'EOROSCO' , '', 'A', '0000000001')

INSERT INTO GEN.USUARIO (CODIGO_PERSONA, CODIGO_USUARIO, CONTRASENIA, ESTADO, CODIGO_PERFIL_USUARIO)
VALUES (2, 'MZAPATA' , '', 'A', '0000000001')

INSERT INTO GEN.USUARIO (CODIGO_PERSONA, CODIGO_USUARIO, CONTRASENIA, ESTADO, CODIGO_PERFIL_USUARIO)
VALUES (3, 'ECONDEZO' , '', 'A', '0000000001')

INSERT INTO GEN.USUARIO (CODIGO_PERSONA, CODIGO_USUARIO, CONTRASENIA, ESTADO, CODIGO_PERFIL_USUARIO)
VALUES (4, 'JRIVAS' , '', 'A', '0000000001')

INSERT INTO GEN.USUARIO (CODIGO_PERSONA, CODIGO_USUARIO, CONTRASENIA, ESTADO, CODIGO_PERFIL_USUARIO)
VALUES (5, 'WCAMAREN' , '', 'A', '0000000001')



